trigger:
  - main

pool:
  vmImage: ubuntu-latest

steps:
  - script: npm install

  - script: npm run build

  - script: npx wrangler pages publish dist --project-name demo --branch $(Build.SourceBranchName) --commit-hash $(Build.SourceVersion) --commit-message "$(Build.SourceVersionMessage)"
    env:
      CLOUDFLARE_API_TOKEN: - task: CloudflarePagesDeploy@0


  - task: CloudflarePagesDeploy@0
    inputs:
      directory: 'dist'
      projectName: 'demo'
      apiToken: '$(CLOUDFLARE_API_TOKEN)'
      accountId: '7ecebcc17ce0ba5fe360c68aaad14501'
