trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: npm install
- script: npm run build
- script: npx wrangler dist --project-name demo --branch $(Build.SourceBranchName) --commit-hash $(Build.SourceVersion) --commit-message $(Build.SourceVersionMessage)